### ISSUE TITLE
[Request] Clear space upon arrival

### ISSUE THREAD

**Issue by Tokeli** [V10lator/V10verlap#1]
I love this mod and can only think of one thing it needs now:

Since the most obvious usage is to go from the floor of one dimension to the ceiling of another, there's generally no open spaces nearby, and you'll spawn inside solid rock.

If there's no open space nearby, it should create a 2-block space for you there. It could have a whitelist/blacklist to prevent it from being used to somehow grief a player's own blocks.

**Comment by V10lator** [comment]
Sorry that it took so long but please test https://minecraft.curseforge.com/projects/v10verlap/files/2627028 and tell me what IDs are missing on the default whitelist. :)

**Comment by ProsperCraft** [comment]
Please also replace the block above the players head with a matching block, I just loaded in to have a gravel block fall on my head.

**Comment by V10lator** [comment]
Both implemented in v5.0 (currently pending on curse)
