### ISSUE TITLE
Invalid Dimension DIM-50

### ISSUE THREAD

**Issue by ProsperCraft** [V10lator/V10verlap#3]
![2018-10-13_22 58 39](https://user-images.githubusercontent.com/4427684/46912759-b0bd0d80-cf3b-11e8-9c33-c7c30970b693.png)

Is there a problem with my syntax?

**Comment by ProsperCraft** [comment]
![2018-10-13_23 36 38](https://user-images.githubusercontent.com/4427684/46912964-e31d3980-cf40-11e8-8ec9-5f5bff5dab8e.png)

**Comment by V10lator** [comment]
Yes, there is a syntax problem. Try it without "DIM", like this:
/v10verlap link 0 -50 251 1

Anyway, I'll keep this open and will handle it as a feature request as I think supporting your syntax is a good idea. :)

**Comment by V10lator** [comment]
With https://minecraft.curseforge.com/projects/v10verlap/files/2627693 your syntax should work, too, but I don't have the time to test it right now. So please reopen in case it still doesn't work.

**Comment by ProsperCraft** [comment]
It must be waiting for approval.  That link doesn't work, I will wait, then test for you.
