### ISSUE TITLE
Brief, massive number of improper mob spawns

### ISSUE THREAD

**Issue by JonJonsonsSon** [V10lator/V10verlap#5]
When using a mod called In Control to adjust which mobs spawn in which dimensions, and V10verlap to connect the overworld to The End, there's a glitch where some mobs you've set to spawn in The End will briefly spawn in massive numbers in the overworld right after you move from The End to the overworld.

**Comment by V10lator** [comment]
Bring that to the devs of the other mod as V10verlap is abandoned! No updates, no bugfixes.
