### ISSUE TITLE
[1.12.2] Server crash - CME- de.v10lator.v10verlap.V10verlap.onWorldTick

### ISSUE THREAD

**Issue by ProsperCraft** [V10lator/V10verlap#7]
https://gist.github.com/ProsperCraft/96ee5bf8ded8cba4fce7038a591ef886

[latest.log](https://github.com/V10lator/V10verlap/files/4057505/latest.log)

Another of the same here - 
https://gist.github.com/ProsperCraft/efeaea4411cc61616e69439c394c0fad

[latest.log](https://github.com/V10lator/V10verlap/files/4057506/latest.log)

**Comment by V10lator** [comment]
This project is abandoned since over a year. I won't touch the codes ever again for private reasons.
That said: Find some other coder who wants to continue this or let it Rest in peace.
