### ISSUE TITLE
[1.12.2] `V10verlap-5.0.jar` unexpected behavior with `aether_legacy-1.12.2-v1.4.4.jar`

### ISSUE THREAD

**Issue by ubergarm** [V10lator/V10verlap#8]
I'm making a Sky Islands themed mod pack, and wanted to stack the Nether at the bottom, the Overworld in the middle, and the Aether Legacy on top.

The Nether part works great after using `WorldgenBlockReplacer-1.12.2-2.2.0.jar` to strip the lid off the Nether!

However, when going from the Overworld up into the Aether while flying mounted on an airship from `davincisvessels-1.12-6.355-full.jar`, the server throws an warning and I do teleport, but instead of arriving at the bottom of the Aether dimension, my `y` value is unchanged and I'm sitting at the top of the Aether dimension...

Warning from my server `Mohist-1.12.2-7bb5453-server.jar`
```
[19:16:20 WARN]: defineId called for: class com.legacy.aether.entities.util.EntityMountable from class com.legacy.aether.entities.util.EntitySaddleMount
```

I did get it to work once by parking the airship and building up and jumping into the Aether, so maybe its related to being mounted?

Finally, I also tried fiddling with the minY value of the Aether, removing the other experiment w/ the End, etc...

For now I'm ditching the Aether and The End trick as the only thing that works reliably is Nether <-> Overworld which is good enough! Thanks!

Here is my config:
```
# The Nether capped to 128 height
-1 {
    S:lower=none
    I:maxY=127
    I:minY=0
    D:scale=8.0
    S:upper=0
}

# The Overworld
0 {
    S:lower=-1
    I:maxY=255
    I:minY=0
    D:scale=1.0
    S:upper=4
}

# The End (this *should* make perpetual falling back into the End itself but doesn't seem to work)
1 {
    S:lower=1
    I:maxY=255
    I:minY=0
    D:scale=1.0
    S:upper=1
}

# The Aether Legacy
4 {
    S:lower=0
    I:maxY=255
    I:minY=0
    D:scale=1.0
    S:upper=none
}
```

**Comment by V10lator** [comment]
Yea, that's clearly related to beging mounted on a davincisvessels-1.12-6.355-full.jar ship. Sadly I abadoned V10verlap long ago (was bigger in the scene when Minecraft wasn't related to Microsoft. Left the sinking ship when bukkit devs... Fucked up cause they where MS employees now... And then, a long time after that, I had a minecraft loving girlfriend. So to make her happy I revived some of my mods / ported them to forge... We broke up around a year ago and... I won't touch these codes ever again).
